#pragma once

#define DEVICE_NAME CONFIG_DEVICE_NAME
#define SAMPLE_SIZE CONFIG_SAMPLE_SIZE
#define WIFI_SSID CONFIG_WIFI_SSID
#define WIFI_PASS CONFIG_WIFI_PASS
#define SERVER_URL CONFIG_SERVER_URL
#define API_KEY CONFIG_API_KEY
